name: 💡 Feature Request
description: | 
  Suggest an idea for this project.
  It's often a good idea to discuss these in our discord first:
  [nflverse discord](https://discord.com/invite/5Er2FBnnQa)
title: "[FEATURE REQ] <title>"
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: |
      Please search to see if an issue already exists for the feature you're requesting.
    options:
    - label: I have searched the existing issues
      required: true
      
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: |
      A clear and concise description of what the problem is, e.g.
      `I'm always frustrated when ...`

- type: textarea
  attributes:
    label: |
      Describe the solution you'd like
    description:  A clear and concise description of what you want to happen.

- type: textarea
  attributes:
    label: |
      Describe alternatives you've considered
    description: |
       A clear and concise description of any alternative solutions or features you've considered.

- type: textarea
  attributes:
    label: |
      **Additional context**
    description: |
      Add any other context or screenshots about the feature request here. 
